version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: x-social-network-container
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
