// Core
import {PropsWithChildren} from "react";
import type {Metadata, NextPage} from "next";
// Global CSS
import "./globals.css";
// Helpers
import {
    geistSans,
    geistMono,
} from '@/helpers/fonts';
import {Providers} from "@/app/providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: NextPage<Readonly<PropsWithChildren>> = ({children}) =>
    <html
        lang="en"
        suppressHydrationWarning={true}
    >
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <Providers>{children}</Providers>
        </body>
    </html>

export default RootLayout;